# Site Settings
title: Max Mendoza
author:
  name: Max Mendoza
  email: your.email@example.com

description: >
  Personal website and blog of Max Mendoza, featuring projects,
  blog posts, and professional experience in mechanistic interpretability
  and AI safety research.

# URL Settings
baseurl: ""
url: "https://maximusmendoza.github.io"

# Build Settings
theme: minima
plugins:
  - jekyll-seo-tag  # Removed jekyll-feed plugin

# Navigation
header_pages:
  - blog.md
  - resume.md

# Social Media Links
minima:
  social_links:
    github: maximusmendoza
    linkedin: your-linkedin-username
    kaggle: your-kaggle-username

# Default Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Max Mendoza
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown Processing
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Sass Settings
sass:
  style: compressed

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md